
pub(super) const RUNTIME_RAMP_MIN_INTERVAL_MS: i64 = 1_200;

pub(super) const RUNTIME_RAMP_MIN_SPEED_BYTES_PER_SECOND: u64 = 2 * 1024 * 1024;

pub(super) const RUNTIME_RAMP_WARMUP_MIN_INTERVAL_MS: i64 = 550;

pub(super) const RUNTIME_RAMP_WARMUP_MIN_SPEED_BYTES_PER_SECOND: u64 = 768 * 1024;

pub(super) const RUNTIME_RAMP_WINDOW_SAMPLES: usize = 3;

pub(super) const RUNTIME_RAMP_HISTORY_RETENTION_MS: i64 = 8_000;

pub(super) const RUNTIME_RAMP_SAMPLE_MIN_INTERVAL_MS: i64 = 200;

pub(super) const RUNTIME_RAMP_FAST_PATH_GAIN_PERCENT: u64 = 45;

pub(super) const RUNTIME_RAMP_FAST_PATH_MAX_TTFB_MS: u64 = 450;

pub(super) const RUNTIME_RAMP_NEGATIVE_GAIN_PERCENT: u64 = 10;

pub(super) const RUNTIME_RAMP_NEGATIVE_GAIN_WINDOWS: u32 = 2;

