pub(super) const RUNTIME_RAMP_MIN_INTERVAL_MS: i64 = 850;

pub(super) const RUNTIME_RAMP_MIN_SPEED_BYTES_PER_SECOND: u64 = 1024 * 1024;

pub(super) const RUNTIME_RAMP_WARMUP_MIN_INTERVAL_MS: i64 = 350;

pub(super) const RUNTIME_RAMP_WARMUP_MIN_SPEED_BYTES_PER_SECOND: u64 = 512 * 1024;

pub(super) const RUNTIME_RAMP_WINDOW_SAMPLES: usize = 3;

pub(super) const RUNTIME_RAMP_HISTORY_RETENTION_MS: i64 = 6_000;

pub(super) const RUNTIME_RAMP_SAMPLE_MIN_INTERVAL_MS: i64 = 150;

pub(super) const RUNTIME_RAMP_FAST_PATH_GAIN_PERCENT: u64 = 30;

pub(super) const RUNTIME_RAMP_FAST_PATH_MAX_TTFB_MS: u64 = 800;

pub(super) const RUNTIME_RAMP_NEGATIVE_GAIN_PERCENT: u64 = 12;

pub(super) const RUNTIME_RAMP_NEGATIVE_GAIN_WINDOWS: u32 = 2;
